### PR TITLE
Bugfix: Bathymetry regridding and B grid velocity regridding. 

### PR DESCRIPTION
**Pull request by ashjbarnes**
at this step the intermediate 'topog_raw.nc' file already has vertical coordinate named elevation. Threw an error when vcoord had different name

### CODE REVIEW

**Comment by navidcy** [comment]
Test fail. Probably the black?
Also, could we change the PR name into something more descriptive?
Otherwise I'm happy to approve as soon as I see tests pass.

**Review by navidcy — APPROVED** [review]
lgtm, let's just rename the PR to something more descriptive.

**Comment by navidcy** [comment]
oh wait, I got confused.... you merged a different PR on this branch?
I think the black formatting is still an issue

**Comment by ashjbarnes** [comment]
Oops sorry Navid you were so speedy! I failed to see that you'd already approved changes

I made another PR to fix an issue with the regridder (Luwei found the bug) and figured they could go together but maybe that was a mistake

**Comment by navidcy** [comment]
Can we enhance the tests so they catch these things or you think it's not worth it?

**Comment by ashjbarnes** [comment]
Yes tests definitely need enhancing to include more edge cases. They're pretty basic for now and even that has been very helpful.

**Comment by navidcy** [comment]
> Oops sorry Navid you were so speedy! I failed to see that you'd already approved changes
> 
> I made another PR to fix an issue with the regridder (Luwei found the bug) and figured they could go together but maybe that was a mistake

All good! :) 

thanks @luweiyang

**Comment by navidcy** [comment]
> Yes tests definitely need enhancing to include more edge cases. They're pretty basic for now and even that has been very helpful.

Well, I was suggesting we enhanced in this PR :)
Perhaps raise an issue to list the things we can improve them.

**Pull request merged**
