### PR TITLE
Automatic PyPI upload on GitHub release

### PR DESCRIPTION
**Pull request by angus-g**
Releases marked as "prerelease" will go to TestPyPI, for workflow testing, etc. Just as an option for #110, probably good to get @dougiesquire's feedback.

### CODE REVIEW

**Comment by angus-g** [comment]
Except for the docs tags (for which I've just added an RTD automation to auto-activate version tags). It does mean you should create new package releases via a GitHub release rather than pushing a tag though.

**Review by dougiesquire — APPROVED** [review]
LGTM

**Comment by navidcy** [comment]
@angus-g, merge?

**Comment by angus-g** [comment]
I'll just do one quick test, then I'll merge!

**Comment by navidcy** [comment]
take your time!

**Comment by angus-g** [comment]
Alright, figured out that we need the `readme` key in the project file, otherwise the workflow will complain. Also fixed a typo. I think this is good to go now!

**Comment by angus-g** [comment]
Should do, yeah.

**Pull request merged**
