### PR TITLE
Enhance (and rename) `nicer_slicer` -> `longitude_slicer`

### PR DESCRIPTION
**Pull request by navidcy**
Closes https://github.com/COSIMA/regional-mom6/issues/32

### CODE REVIEW

**Comment by navidcy** [comment]
I noticed

https://github.com/COSIMA/regional-mom6/blob/544eb434ad1029231b436f7a7891f4ad0b92692a/regional_mom6/regional_mom6.py#L207

Let's add an `assert` to ensure our assumption is correct!

**Comment by navidcy** [comment]
I also noticed 

https://github.com/COSIMA/regional-mom6/blob/544eb434ad1029231b436f7a7891f4ad0b92692a/regional_mom6/regional_mom6.py#L161

Why isn't `[0, 360]` not part of the "commonly used domains"?

**Comment by navidcy** [comment]
I think `nicer_slicer` should be renamed to `longitude_slicer`, right?

**Comment by navidcy** [comment]
Question:

Here:

https://github.com/COSIMA/regional-mom6/blob/544eb434ad1029231b436f7a7891f4ad0b92692a/regional_mom6/regional_mom6.py#L165-L176

we mention `oldx` but I don't see any `oldx` in the source code. Is the `oldx` only for reference in the docstring or was there an `oldx` variable at some point that got deprecated?

**Comment by navidcy** [comment]
Ideally this PR should also deal with #118

**Review by ashjbarnes — APPROVED** [review]
Looks good. Might need to merge renaming to longitude_slicer will merge nicely with #122

**Pull request merged**
